### ISSUE TITLE
Combat Log

### ISSUE THREAD

**Issue by oceancubes1** [blay09/HardcoreRevival#101]
### Minecraft Version

1.19.2 (LTS)

### Mod Loader

Fabric

### Mod Loader Version

0.14.19

### Mod Version

9.0.2

### Balm Version

4.5.7

### Describe the Issue

Great Mod
I want to add it for my fabric 1.19.2 PvP server but it's has a conflict with Combat Log mod, whan it should instantly kill player, when he logouts while PvP. Is it possible to fix that?

https://modrinth.com/mod/combatlog

**Comment by BlayTheNinth** [comment]
> has a conflict with Combat Log mod

What does that mean? What actually happens and what do you expect to happen?
