### ISSUE TITLE
make mobs ignore you when downed

### ISSUE THREAD

**Issue by slovinsqui** [blay09/HardcoreRevival#105]
When downed, mobs still attack you, making armor break really quick, plus since they are still hard focusing you, other players can kill them in a cheesy way

**Comment by SanicFan19** [comment]
This mod is almost unplayable with the mobs still targeting you, especially when you have mods that make mobs target you from farther away. This need to be fixed ASAP. I would use another mod but the only other one I can find doesn't work for me

**Comment by slovinsqui** [comment]
or at least adding an option to make the player invincible
