### ISSUE TITLE
Haema vampire players can't die

### ISSUE THREAD

**Issue by thedeerirty** [blay09/HardcoreRevival#107]
### Minecraft Version

1.19.2 (LTS)

### Mod Loader

Fabric

### Mod Loader Version

0.14.21

### Mod Version

9.0.2.

### Balm Version

4.5.7.

### Describe the Issue

Hi! I've already brought this issue up to Haema's author, twice now, as I had noticed this when using both together back in 1.18.2. 

Simply put, vampirism from Haema prevents any form of death with your mod here. Normally, Haema vampirism is supposed to make the player immune _certain_ kinds of death, such as normal weaponry. But things such as the sunlight, or smite-enchanted weapons, should kill them. This is not the case. 

I think it may be more of an issue on Haema's end - something about it preventing a vampire player from actually dropping to zero hearts (thus not triggering the bleedout state), but I thought I might bring it up here.

**Comment by BlayTheNinth** [comment]
Closing since 1.19 is no longer supported.
