### ISSUE TITLE
Item disappears when dropped while knocked out

### ISSUE THREAD

**Issue by V-lpen** [blay09/HardcoreRevival#112]
### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Mod Loader Version

1.20.1

### Mod Version

12.0.0+fabric-1.20

### Balm Version

1.20.1-7.1.4

### Describe the Issue

If you press drop on an item while dead, the item disappears from existence

**Comment by BlayTheNinth** [comment]
Dropping of items is disabled on the client side and if drops do somehow go through to the server, they are reverted by adding the item back into the player's inventory. I cannot reproduce the issue described. Something in your instance must be changing the behavior of item drops significantly.
