### ISSUE TITLE
Incompatibility with Body Health System

### ISSUE THREAD

**Issue by jrcarl624** [blay09/HardcoreRevival#113]
### Minecraft Version

1.20.1 (LTS)

### Mod Loader

Fabric

### Mod Loader Version

Normal

### Mod Version

12.0.1+fabric-1.20.1

### Balm Version

7.2.1+fabric-1.20.1

### Describe the Issue

No revival when used with https://github.com/SrGnis/Body-Health-System/tree/main

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

Sodium

**Comment by BlayTheNinth** [comment]
Hardcore Revival relies on damage events whereas Body Health System completely replaces damage and manages the player's health value directly. There's nothing reasonable I can do on my side to make it work, it would need Body Health System to fire a damage event (e.g. with a custom damage type that they can then ignore).

**Comment by jrcarl624** [comment]
I will make an issue within their repo
