### ISSUE TITLE
1.20.1 First Aid mod compatibility

### ISSUE THREAD

**Issue by DogeKingChris** [blay09/HardcoreRevival#121]
All the other revive mods are broken right now, and don't work with First Aid even when they have explicit compatibility with the mod. I'm looking for a good revive mod which I can safely use in my modpack along with First Aid. This mod and Incapacitated are my top 2 favorite revive mods.

**Comment by BlayTheNinth** [comment]
See #66. Hardcore Revival provides events necessary for mods to become compatible, but compatibility would be better implemented inside First Aid so that Hardcore Revival doesn't have to replicate third party mod logic.
