### ISSUE TITLE
Behavior improvement with the Inventory Totem mod

### ISSUE THREAD

**Issue by TsplayerT** [blay09/HardcoreRevival#123]
### Minecraft Version

1.20.1 (LTS)

### Mod Loader

Fabric

### Mod Loader Version

0.15.10

### Mod Version

12.0.2

### Balm Version

7.2.2

### Describe the Issue

When the player dies, the accept their fate screen appears before the **Inventory Totem** mod revives the player with the _Totem_ item.

**Comment by drakray** [comment]
I seem to be having the same problem, with the 1.21 version for fabric 0.16.10
