### ISSUE TITLE
Behavior improvement with the Better Totem of Undying mod

### ISSUE THREAD

**Issue by TsplayerT** [blay09/HardcoreRevival#124]
### Minecraft Version

1.20.1 (LTS)

### Mod Loader

Fabric

### Mod Loader Version

0.15.10

### Mod Version

12.0.2

### Balm Version

7.2.2

### Describe the Issue

When the player dies, the fate acceptance screen appears before the Better Totem of Undying mod revives the player with the Totem item

**Comment by BlayTheNinth** [comment]
Cannot reproduce, likely fixed elsewhere since report.
