### ISSUE TITLE
crash with lightwithin

### ISSUE THREAD

**Issue by pocinhas** [blay09/HardcoreRevival#131]
### Minecraft Version

1.20.1 (LTS)

### Mod Loader

Fabric

### Mod Loader Version

0.15.11

### Mod Version

12.0.4

### Balm Version

7.3.6

### Describe the Issue

server crash relating to a knocked down player, when in junction with the [LightWithin](https://modrinth.com/mod/lightwithin) mod. should i report this to them instead?

### Logs

https://pastebin.com/Su7HcPyF

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

some server-side yes, but i didnt see any mention of them on log

**Comment by BlayTheNinth** [comment]
Yes, this issue is caused by Dummmmmmy/Moonlight Lib and must be reported to them.
