### ISSUE TITLE
Suggestion: change the death animation to the one from Minecraft Dungeons

### ISSUE THREAD

**Issue by ArduFish** [blay09/HardcoreRevival#132]
I would suggest changing the player death animation to the one from Minecraft Dungeons. ([https://minecraft.wiki/w/File:HexDownedFloor_(Dungeons).gif](https://minecraft.wiki/w/File:HexDownedFloor_(Dungeons).gif))

**Comment by BlayTheNinth** [comment]
Adding new animations is out of scope for this mod.
