### ISSUE TITLE
Invulnerable when infected with Hordes mod

### ISSUE THREAD

**Issue by Ten-jen** [blay09/HardcoreRevival#134]
### Minecraft Version

1.20.1 (LTS)

### Mod Loader

Forge

### Mod Loader Version

47.3.5

### Mod Version

12.0.4

### Balm Version

7.3.6

### Describe the Issue

If you have "the hordes" mod enabled. And you become infected. If that infection lasts long enough to kill you. The hardcorerevival mod still lets you go down. If a player revives you however, you'll have the respawned HP, but if you die again. You wont go down or die. You are stuck with no HP, cant pick up XP or Items, and you can't open your inventory or interact with anything. You viewpoint also bugs out.  (this can also be replicated using the /effect give [username] hordes:infected 20 4     then when you go down typing /revive,  then /kill and youll enter the same state again. you can keep typing /revive to temporarily fix the issue until you die again and it re-activates the problem even without the status effect.

A proposed fixed for this would allowing modpack creators or players to define status effects that'll skip the revive screen from appearing and just allowing the player to die.

### Logs

https://gist.github.com/Ten-jen/c6230b219cbd2a3fc2943408bd0e8432

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

We have alot, but the revive mod works fine unless you get the infected effected

**Comment by BlayTheNinth** [comment]
Testing this in 1.21.1, it looks like Hordes is causing an infinite death loop by constantly re-adding the infection effect and re-killing the player when it expires. That is inherently incompatible with Hardcore Revival.

One possible workaround would be adding `hordes:infection` to the `instantDeathSources` option in your Hardcore Revival config.
