### ISSUE TITLE
Dying in nether teleports player

### ISSUE THREAD

**Issue by Xatrongamer** [blay09/HardcoreRevival#135]
### Minecraft Version

Other (specify below)

### Mod Loader

Forge

### Mod Loader Version

1.12.2

### Mod Version

1.2.0

### Balm Version

No balm for 1.12.2

### Describe the Issue

Dying in the nether teleports the player to the overworld in another location

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

No, only hardcore revival

**Comment by BlayTheNinth** [comment]
Minecraft 1.12.2 is 7 years old and no longer supported.
