### ISSUE TITLE
Something about chests

### ISSUE THREAD

**Issue by KhriszB** [blay09/HardcoreRevival#138]
> Note that modders will NEVER ask you to download and run executable files! Do not fall for malicious spambots!
Hey! Love your mod! I use it in my 1.20.6 server. 
But I want to do something with lazy people. They leave their chests around and I want them to learn to not do it. 
It hink that would be a cool option in config menu to: 
1.) Enable chest auto break
If the player opened their chest it would destroy itself
OR
2.) Chest limit 
You need to get your stuff back couse only one (or more depends on the config) chest(s) allowed for once
3.) Chest timer 
You can set a custom timer which count down and if it reaches 0 the chest vanishes

Sorry for bad English and ideas. I try to find a solution (And nerf at the same time) for the chests lazy people leave around the world and causes lag. Number 3 would be awesome. 

Thanks

Have great morning/day/evening/year :D

**Comment by BlayTheNinth** [comment]
Anything related to what players may or may not do with chests is far out of the scope of this mod.
