### ISSUE TITLE
Totem of Undying(Vanilla) didnt work sent directly into the delete hardcore world prompt.

### ISSUE THREAD

**Issue by rogalik27** [blay09/HardcoreRevival#142]
### Security Notice

- [X] Users might post VIRUS LINKS in comment responses to issue reports. **DO NOT DOWNLOAD ANY FILES FROM HERE.**

### Minecraft Version

Other (specify below)

### Mod Loader

Fabric

### Mod Loader Version

0.16.7

### Mod Version

14.0.2

### Balm Version

idk

### Describe the Issue

Upon using a Totem of undying from vanilla (my friend held it and i wanted to test it out by killing them) i quickly found out that it doesnt function properly. After i landed the last blow the animation and particles of the reviving played, but my friend died directly into the "Spectate World" or "Title Screen" without even getting a prompt from the mod to give up. I am very much looking forward to giving further needed information to reproduce the bug.

### Logs

it went like
player_nickname died (probably a prompt from the mod)
player_nickname was killed by my_nickname (the vanilla kill feed message)

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge or Arclight)?

Sodium, Immediately Fast

**Comment by BlayTheNinth** [comment]
Closing as likely duplicate of #141 and since Minecraft 1.20.4 is no longer supported.
