### ISSUE TITLE
Timer should be more than 120 sec. Also, please, compatibility with LuckPerms!

### ISSUE THREAD

**Issue by SnzMaxim** [blay09/HardcoreRevival#143]
Would be great to create group of died players in LuckPerms.
Its would give great customization in other server-side mods. Like highlighting players in game TAB(by rules, placeholders, etc.)

**Timer always is 120 sec**. I dont know its a bug or something else
But, regardless of the timer value in config, thats what is shown to players - always 120 sec. Even if i turn it off.

well... version 1.20.1, i didnt tested others. Then sorry if it already fixed.

**Comment by BlayTheNinth** [comment]
Closing for not following the bug template that asks the necessary information for bugs to be fixed.
