### ISSUE TITLE
Cannot look around or unarmed attack.

### ISSUE THREAD

**Issue by heromedel** [blay09/HardcoreRevival#148]
### Minecraft Version

1.21.3

### Mod Loader

Fabric

### Mod Version

21.3.4

### Describe the Issue

I turned on the setting for allow unarmed melee and then we tested it and all it had was the cursor and accept your fate, so we turned off accept your fate and reloaded the server and it still showed accept your fate, in both situations only a cursor and no ability to look around or strike. We even tried it on server and client with matching settings.

### Logs

[2024-12-08-3.log.gz](https://github.com/user-attachments/files/18057487/2024-12-08-3.log.gz)

**Comment by BlayTheNinth** [comment]
You have to press Escape to exit out of the death screen in order to look around.
