### ISSUE TITLE
Print the actual death cause in chat

### ISSUE THREAD

**Issue by Defetyre** [blay09/HardcoreRevival#149]
Death messages are essential to the game's charm, but this mod seems to overwrite some of them

**Comment by BlayTheNinth** [comment]
Elaborate?

**Comment by Defetyre** [comment]
With your mod installed sometimes death messages are just "Player died"

**Comment by BlayTheNinth** [comment]
Closing for lack of information. If there is an issue, fill out the bug report form and provide steps to reproduce.
