### ISSUE TITLE
Player Respawn

### ISSUE THREAD

**Issue by firyy** [blay09/HardcoreRevival#31]
Config option to revive the player on the coords he died would be extremely...good.

**Comment by BlayTheNinth** [comment]
That is already the default behaviour.

**Comment by firyy** [comment]
Not for the 1.12.2 version at least

**Comment by BlayTheNinth** [comment]
It is the default for 1.12.2 too, unless you have some other mods changing respawn behaviour. In 1.14+ the rescueing has been changed to no longer respawn the player, so the issue won't be present there anymore.
