### ISSUE TITLE
Forge broke the "Accept your Fate" button again.

### ISSUE THREAD

**Issue by CravenInsomniac** [blay09/HardcoreRevival#34]
My Forge Version is 31.1.44 and Hardcore Revival's Version is 4.0.0.

Situational Context: I used the "/kill" command from Ma Essentials.

Upon dying I was brought to Revival's screen with the "Accept your Fate" button and my screen was jittering from using the /kill command. Everything was normal. Hit accept my fate and nothing. Seeing as this has happened before I can only assume forge screwed something up again.

**Comment by CravenInsomniac** [comment]
I think I might have found a part of the issue. Does Hardcore Revival respawn a person at the exact coordinates of their death, or at the closest safe position? I'm making a community-focused modpack with added mods, and one of those mods is the Gravestone mod to alleviate the concerns of solo players. Is it possible that the gravestone spawning is causing unintended issues?

**Comment by mr-poyo** [comment]
I also get this bug in forge 31.1.49. I'm only able to respawn after clicking the Accept your Fate, then hitting "escape" on the keyboard. :c
