### ISSUE TITLE
Mobs cancelling res timer when punched and already down

### ISSUE THREAD

**Issue by syndicate25** [blay09/HardcoreRevival#38]
If you are waiting for someone to come pick you up with a res timer, if a mob attacks you during that time, you die permanently.

**Comment by syndicate25** [comment]
Additionally, if you log out and back in again, then it seems to fix this. Meaning, you're back to being in a state where you can be rescued, and your timer starts over.

**Comment by BlayTheNinth** [comment]
What Minecraft version was this on? Normally mobs can't target you while you're dead, and any attacks are cancelled as well so it shouldn't be possible unless there was some other mod changing that behaviour.

There was another bug where the timer wouldn't actually reset after being rescued, so if you'd die again it'd only have the remaining time left (even though it always displayed the full timer). Could that have been the case here maybe?
