### ISSUE TITLE
Respawn after death

### ISSUE THREAD

**Issue by ghost** [blay09/HardcoreRevival#40]
Hello, my Problem is that when I die, i can respawn after the timer runs out.(or after early-accepting)

**Comment by ghost** [comment]
I tested the mod in singleplayer

**Comment by ghost** [comment]
Or do you have to choose hardcore gamemode to die?

**Comment by BlayTheNinth** [comment]
Yes, this mod does not add hardcore deaths itself, only the revival from them.

**Comment by ghost** [comment]
Ah ok, I thaught
