### ISSUE TITLE
Non-vanilla resurrection "bricks" the player

### ISSUE THREAD

**Issue by Kai-Kramer** [blay09/HardcoreRevival#43]
### Description
Non-vanilla resurrection (tested Curio of Undying (curio slot) and Angelheart Vial (anywhere in inventory) both put the player in a weird state. Both the Angelheart vial and Curio of Undying don't activate until *after* `Accept your Fate` is chosen, if not held in a hand.

Players still have health and can die again, but are stuck in the respawn screen unless the world is reloaded (exit to title -> rejoin.) However, once the world is reloaded, the player is effectively invisible and cannot move, but can access their inventory and several other GUIs. The screen jitters (annoyingly) and the only way to resolve this is to die a second time and respawn.

Video showcasing this [here](https://www.youtube.com/). 

This does not cause a crash.
### Version and Modlist
Forge 31.2.36
Hardcore Revival 4.0.2
Curio of Undying 3.0 -- Used for Curio of Undying
Reliquary 1.3.4.995 -- Used for Angelheart Vial
Curios API 2.0.2.6 -- Dependency

**Comment by marewey** [comment]
Having a very similar issue, only opening gui does crash client
