### ISSUE TITLE
Epic Fight Mod Incompatible

### ISSUE THREAD

**Issue by AriaThePeryton** [blay09/HardcoreRevival#51]
There seems to be an issue with Epic Fight Mod,
When revived, you aren't able to scroll/select/look around 
even going as far as to soft locking the game
Epic Fight Mod seems to be the culprit.
Was wondering if there is a possible fix for this?
Video demonstrating this is linked [here](https://youtu.be/NIg-kL3FgUs)

**Comment by rad001** [comment]
My wife and I are running into this issue as well, but this pinpoints which mod incompatibility is causing it. In our cause, to fix it, we revive each other and have to completely close out of MC and join again. With having nearly 100 mods installed, it takes a while on slower machines.

**Comment by usa11131519** [comment]
I got the same problem as u, epic fight mod cause player that was revived not able to move or even select anything.

**Comment by BlayTheNinth** [comment]
Epic Fight Mod still acts kinda weird in regards to the downed animation in the new beta of Hardcore Revival, but at least it shouldn't have any gamebreaking issues anymore now.

**Comment by CreatopiaUK** [comment]
yoyo, i have a mod that already fixes MOST issues with HC revival. I can add a feature in my next update to solve this if it is still an issue? :P 
here's the mod!: https://www.curseforge.com/minecraft/mc-mods/death-detangler
Also if you need it ported to another version just ask! :)
