### ISSUE TITLE
can't die with shield mechanics in the same instance

### ISSUE THREAD

**Issue by Aer-ink** [blay09/HardcoreRevival#55]
it seems like there is a problem with the mod shield mechanics if you get K.O. while holding a high tier shield like the netherite one from spartan shields you can't give up and you will keep reviving with 1hp if you try to, it becomes a loop of K.O.s. when you die.

**Comment by Romulus96** [comment]
This is still an issue with the newest version of this mod. I opened an issue on the shield mechanics repo, maybe this problem can be solved by the author there.
