### ISSUE TITLE
HardcoreRevival causes Personality mod to desync

### ISSUE THREAD

**Issue by floral-qua-floral** [blay09/HardcoreRevival#56]
[Personality](https://www.curseforge.com/minecraft/mc-mods/personality) is a mod that adds a keybind to enter the crawling position. Installing HardcoreRevival alongside it introduces a bug to Personality in which right-clicking while crawling causes the player to stand up server-side, while remaining in the crawling state client-side. The issue is very temporary in nature; simply releasing the Crawl keybind restores agreement between the client and server.

Steps to reproduce:

1. Install the [Personality](https://www.curseforge.com/minecraft/mc-mods/personality) mod alongside HardcoreRevival
2. Enter a world and construct a one-block-high gap that can only be entered by crawling.
3. Hold the crawl keybind, then right click (with any item, or with an empty hand). Observe that the camera position jolts upwards before sinking back down again. (It appears that the bug specifically occurs upon _releasing_ right-click.)
4. Attempt to crawl into the one-block gap. Observe that the player rubber-bands back out due to client-server desync.

I've also reported this issue on the Personality issues page, since I am not sure which side this issue would be best solved from. The corresponding issue report is [here.](https://github.com/team-abnormals/personality/issues/24)

**Comment by BlayTheNinth** [comment]
I believe this is fixed in more recent versions, as the pose is now only affected on right click if there is actually someone to rescue in range.
