### ISSUE TITLE
Nothing happens when holding RMB on a dead player

### ISSUE THREAD

**Issue by Tronnic** [blay09/HardcoreRevival#60]
### Minecraft Version

1.18.1

### Mod Loader

Forge

### Mod Loader Version

39.0.7

### Mod Version

hardcorerevival-forge-1.18-8.0.0

### Describe the Issue

Hi, when a player dies, nothing happens when RMB is held. Timer of the dead player is ticking down. We installed the mod both on client & serverside. We're running a GPortal-Server with Forge.

Other mods we have running:

balm
dynview
easiersleeping
fallingtree
inventorysorter
jei
journeymap
serertabinfo
waystones

Thanks for any help!

Here's the server-log with startup and playerdeath. Everything seems to be running normal:

### Logs

Server Startup: https://pastebin.com/pRU9UD9W
Hardcore-Revival Settings: https://pastebin.com/5BBga2TE
### Do you use any performance-enhancing mods (e.g. OptiFine)?

We use optifine & shaders, disabling them did not help.

**Comment by Calibrumm** [comment]
bumping this. having the same issue on 1.18.1. we have multiple mods but none that would interact with this one.

**Comment by Master-64** [comment]
Bumping as well. Issue is still present.

**Comment by K1Crawford** [comment]
Created a Github account JUST to say that this issue is still happening. Maybe the ability to change the keybind would be helpful too?, Either way... Issue is still present
mc 1.18.1
fabric loader 13.3
