### ISSUE TITLE
One hit ko in AQM2

### ISSUE THREAD

**Issue by itsdinkd** [blay09/HardcoreRevival#61]
### Minecraft Version

1.18.x

### Mod Loader

Fabric

### Mod Loader Version

12.0.12

### Mod Version

Latest

### Describe the Issue

Only happens in a server instance. I added Hardcore Revival Fabric into my modpack, Another Quality modpack 2. Since adding, I've been getting reports by players who play on servers and our own official servers that they have been getting one hit ko'd by mobs. 

Turns out, this was due to Hardcore Revival

What is happening is when the players health amount aligns with the mob or a tool/weapon damage amount, they instant down. 

Steps to reproduce;
1. Start up local or dedicated server
2. Have a player or mob next to you.
3. Allow them to attack you
4. Watch your hearts, once it gets to the value of the thing attacking you, you will down.

**Comment by itsdinkd** [comment]
https://github.com/ModdingForBlockheads/HardcoreRevival/issues/52 pretty sure this is why. Hardcore Revive is not factoring in armor when the players health is the same as the damage

**Comment by BlayTheNinth** [comment]
This has been fixed in Balm 2.4.0
