### ISSUE TITLE
Player respawns instantly

### ISSUE THREAD

**Issue by Dxas** [blay09/HardcoreRevival#63]
### Minecraft Version

1.16.x

### Mod Loader

Forge

### Mod Loader Version

36.2.23

### Mod Version

HardcoreRevival_1.16.5-6.0.1.jar

### Describe the Issue

I have a minecraft server with friends and one person has this bug. When he goes down he instantly gets revived for some reason. With everyone else it works fine.

### Do you use any performance-enhancing mods (e.g. OptiFine)?

OptiFine

**Comment by BlayTheNinth** [comment]
Does this happen on Minecraft 1.19?
