### ISSUE TITLE
Incompatibility with Heart Aspect: Totem from Victus

### ISSUE THREAD

**Issue by TheButterbrotMan** [blay09/HardcoreRevival#64]
### Minecraft Version

1.18.x

### Mod Loader

Fabric

### Mod Loader Version

0.12.12

### Mod Version

8.0.0

### Describe the Issue

Just found that the Heart Aspect: Totem from Victus seems not to work properly with Hardcore Revival, both are mods in the modpack, so I guess it's worth noticed. 
When launching with Victus alone, the Aspect can prevent player from death when taking lethal damage (e.g. /tp <self> ~ ~200 ~ for a 200-block-high fall damage), regardless of having a Totem of Undying in the inventory or not. However,  launching both mods under the exactly same Aspect setup and damage taken, the Aspect will break but might not be activated, and the player will die. I haven't had time to open an issue on their Github pages, but I'm planning to do so.

**Comment by TheButterbrotMan** [comment]
https://github.com/Samekichi

**Comment by TheButterbrotMan** [comment]
[Samekichi](https://github.com/Samekichi)

**Comment by BlayTheNinth** [comment]
Looks like this was resolved on Victus' side
