### ISSUE TITLE
K.O. players can use items from Vic's Modern Warfare Mod

### ISSUE THREAD

**Issue by Waytyx** [blay09/HardcoreRevival#65]
### Minecraft Version

1.12.x

### Mod Loader

Forge

### Mod Loader Version

14.23.5.2854

### Mod Version

1.12.2-1.2.0

### Describe the Issue

Hi, I have a problem that players while being dead and spectating, their key presses still interacts with their items. I use Vic's Modern Warfare Mod(2.0-0.4.6.2) and player while being dead can left click, right click, press R, ... and fire the weapon or throw grenades etc.

If it can't be fixed could there be an option in config to turn off spectating? Because this can't happen while being in death screen.

**Comment by BlayTheNinth** [comment]
1.12 is no longer supported and it doesn't look like Modern Warfare is updating to recent versions.
