### ISSUE TITLE
Compatibility with First Aid body health

### ISSUE THREAD

**Issue by ghost** [blay09/HardcoreRevival#66]
The First Aid mod is a very popular mod, changing the health system to use a Body-Part system instead of vanilla.

While Hardcore Revival functions with First Aid installed, it doesn't work great upon revival.

For example, you can get revived and immediately die again, since the distribution of "replenished health" from Hardcore Revival is randomized into a different body part.

It would be awesome to see compatibility between the two, allowing for customization of how many hearts per body part / which body part are replenished.

https://www.curseforge.com/minecraft/mc-mods/first-aid

**Comment by BlayTheNinth** [comment]
I've added two new API Events that fire when players get rescued / revived for 1.20.4. I believe compatibility would be best done on First Aid's side so that Hardcore Revival doesn't have to know about First Aid internals.
