### ISSUE TITLE
Ceaseless Impetus (Totem of Undying-like) from Malum has no effect

### ISSUE THREAD

**Issue by LunarFactory** [blay09/HardcoreRevival#67]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

39.0.75

### Mod Version

8.0.0 / 1.2.0(Malum)

### Describe the Issue

In Malum mod, there is a Ceaseless Impetus, which revives player twice. However, it does not work with Hardcore Revival.
Totem of Undying worked well.

### Logs

No errors.

### Do you use any performance-enhancing mods (e.g. OptiFine)?

Rubidium 0.4.0e / Radium 0.7.7g

**Comment by BlayTheNinth** [comment]
Closing since the item was removed from Malum.
