### ISSUE TITLE
Accepting Fate with Shield Mechanics shield in hand instantly revives

### ISSUE THREAD

**Issue by ProNoob145** [blay09/HardcoreRevival#68]
### Minecraft Version

1.16.x

### Mod Loader

Forge

### Mod Loader Version

forge-36.2.20

### Mod Version

HardcoreRevival_1.16.5-6.0.1

 I am using Minecraft 1.16.5. HardcoreRevival_1.16.5-6.0.1 shieldmechanics-2.8-1.16.5

### Describe the Issue

I have found one issue if you use this mod together with another mod, Shield mechanics. If both mods are installed and a player is knocked out with a modded shield or vanilla shield in main hand or off hand and then it clicks accept your fate, player instantly stands up with half heart (or another value in config) like if somebody picked you up, in other words, if player dies with a shield in hand, it becomes immortal!

### Logs

https://pastebin.com/kp8tPuvu

### Do you use any performance-enhancing mods (e.g. OptiFine)?

OptiFIne Performant FerritCore chunksavingfix flywheel

**Comment by ThanEEpic** [comment]
Getting the same with the same version as mentioned by OP.

**Comment by BlayTheNinth** [comment]
This seems to have resolved itself in 1.20, can no longer reproduce
