### ISSUE TITLE
(Forge 1.12.2) this mod completely breaks iChun's sync mod.

### ISSUE THREAD

**Issue by LostGameDev** [blay09/HardcoreRevival#69]
### Minecraft Version

1.12.x

### Mod Loader

Forge

### Mod Loader Version

14.23.5.2860

### Mod Version

1.2.0

### Describe the Issue

video of the issue: https://www.youtube.com/watch?v=Pwy0PN08sYU&ab_channel=GameWorldStuff

**Comment by BlayTheNinth** [comment]
Minecraft 1.12 is no longer supported
