### ISSUE TITLE
Incompatibility bug with PassiveShield causing infinite self-revive

### ISSUE THREAD

**Issue by ThanEEpic** [blay09/HardcoreRevival#71]
### Minecraft Version

1.16.x

### Mod Loader

Forge

### Mod Loader Version

36.2.34

### Mod Version

6.0.1

### Describe the Issue

When K.O.d while holding a shield in either hand, Accept Your Fate button infinitely returns player to life at half a heart. It seems to be tied to the use of the PassiveShields mod(version 1.16.5-2.0).

### Do you use any performance-enhancing mods (e.g. OptiFine)?

Rubidium + Magnesium

**Comment by BlayTheNinth** [comment]
This seems to have resolved itself in 1.20, can no longer reproduce
