### ISSUE TITLE
Revival countdown is sometimes circumvented

### ISSUE THREAD

**Issue by Ceifeire** [blay09/HardcoreRevival#72]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

40.1.30

### Mod Version

8.0.1

### Describe the Issue

When being dealt lethal damage by a mob from Alex's mobs it does not trigger the revival countdown. Any other method of death causes players to go down and trigger the timer.

**Comment by Ceifeire** [comment]
Having now played with this mod for over a week there seem to be other things that can circumvent the timer. Sometimes vanilla mobs circumvent it. I have uploaded an exported profile from the curseforge desktop app so you can have the full mod list.

[SOGE Testing 1.18.2-1.0.zip](https://github.com/ModdingForBlockheads/HardcoreRevival/files/9023799/SOGE.Testing.1.18.2-1.0.zip)

**Comment by BlayTheNinth** [comment]
Closing since 1.18 is no longer supported and there haven't been any recent reports of this happening.
