### ISSUE TITLE
Downed player coordinates/tell people they can hit escape to look around and open f3

### ISSUE THREAD

**Issue by GrandmaPork** [blay09/HardcoreRevival#76]
1.18.2 could you make a config that when toggled, it automatically sends the player's coordinates in chat? Would be very useful. Also, it took me way too long to realize hitting escape allows you to look around and stuff so making that more clear upon being downed would be nice.

**Comment by BlayTheNinth** [comment]
People generally find out about being able to ESC from the K.O. screen by just trying, so I don't think they need to be specifically told.

The F3 screen is a debug screen that happens to also show coordinates, so I'm not super keen on adding features that rely on it. However, Hardcore Revival did use to have support for a now no longer updated mod that would ping the location. Perhaps there is mods like that that can be integrated, or support could be added for minimap mods to add a temporary waypoint when the downed player presses a "ping" button on the death screen. But for now, I'm moving this over to Discussions.
