### ISSUE TITLE
1.18.2 EPIC FIGHT MOD COMPATIBILITY

### ISSUE THREAD

**Issue by NicoTheIdiot** [blay09/HardcoreRevival#78]
Forge 1.18.2 - 40.1.80

When using the Epic Fight mod,when a player is down he can still attack when in combat mode.

To recreate this bug,just launch the game with Hardcore Revival and Epic FIght installed,die and click the combat mode switch (by defaut,R) and attack a mob or another player. You can still attack.

**Comment by BlayTheNinth** [comment]
This seems to have resolved itself in 1.20, can no longer reproduce
