### ISSUE TITLE
Revived player is resurrected not where they die.

### ISSUE THREAD

**Issue by Lodac77** [blay09/HardcoreRevival#79]
When getting a downed player back up, they sometimes get up in an area where they did not die. Sometimes next to their bed where they set spawn, a waystone, or where they originally started when they joined the world.
Edit: Playing with RLCraft Modpack 1.12 (Latest), no I am not using playerrevival by CreativeMD mod.

**Comment by Lodac77** [comment]
Here's some more info...
### Minecraft Version
1.12.2

### Mod Loader
Forge

### Mod Loader Version
Forge Loader 14.23.5.2860

### Mod Version
HardcoreRevival_1.12.2-1.2.0

### Describe the Issue
When a player dies and is revived, sometimes when they get up they teleport to a specific area as if they died and were revived there. When in the End they end up being next to their bed. Last night I played with a friend and they died in a ravine, when I got them up they disappeared instantly and ended up next to the village well, supposedly where they spawned in when logging on to the server.

### Logs
I only have a list of the mods I am using. When checking the logs, there is nothing that is output by the game or my server. I am currently playing on RLCraft the modpack, latest release. I have added a couple of mods and changed their configs. Obviously, Hardcore Revival is one of those mods. The mod intended for this modpack, Playerrevival by CreativeMD, is also not present due to worse bugs than this. 

`minecraft, mcp, FML, forge, creativecoredummy, entity_culling, itemphysic, ivtoolkit, foamfixcore, tnt_utilities_core, adhooks, advanced-fishing, aireducer, alcatrazcore, antiqueatlas, antiqueatlasoverlay, anvilpatch, aquaacrobatics, aquaculture, armorunder, astikorcarts, autoreglib, base, battletowers, baubles, bedbreakbegone, mujmajnkraftsbettersurvival, bettercaves, bettercombatmod, betterfoliage, bettermineshafts, betternether, betterquesting, bettertabs, blockoverlayfix, bloodmoon, bnbgaminglib, bountifulbaubles, bountiful, bq_msi, bqtweaker, callablehorses, carrots, carryon, charm, chunkanimator, classyhats, collisiondamage, comforts, compatskills, contenttweaker, controlling, coralreef, corpsecomplex, cosmeticarmorreworked, craftablechainmail, craftablehorsearmour, craftpresence, ctgui, crafttweaker, crafttweakerjei, creativecore, custommainmenu, cyclicmagic, defiledlands, disenchanter, dldungeonsjbg, dsurround, dynamictrees, dynamictreesdefiledlands, dttraverse, elenaidodge, enchdesc, enhancedvisuals, familiarfauna, fbp, fantasticlib, firstaid, fishingmadebetter, foamfix, foodexpansion, forgeendertech, forgelin, forgottenitems, friendlyendermite, cfm, fxcontrol, globalgamerules, googlyeyes, grapplemod, hardcorerevival, iceandfire, ichunutil, infernalmobs, inspirations, inventorytweaks, iseedragons, itlt, jei, levelup2, librarianliblate, librarianlib, loadingscreens, locks, loottweaker, lostcities, lycanitesmobs, mainmenuscale, mantle, mcwbridges, testdummy, mobends, modtweaker, mousetweaks, mtlib, multimine, neat, notreepunching, particleculling, pigstep, placebo, playerbosses, potioncore, potionfingers, qualitytools, quark, realistictorches, reborncore, reccomplex, reskillable, resourceloader, rltweaker, roguelike, roughtweaks, ruins, rustic, scalinghealth, sereneseasons, setbonus, shieldbreak, silentlib, simpledifficulty, sit, snowrealmagic, somanyenchantments, soundfilters, spartandefiled, spartanfire, spartanhudbaubles, spartanshields, spartanweaponry, spawnercontrol, srparasites, bq_standard, switchbow, tickprofiler, tnt_utilities, toastcontrol, toolbelt, traverse, xat, trumpetskeleton, tschipplib, tumbleweed, variedcommodities, waystones, wearablebackpacks, wolfarmor, xpfromharvest, xpbook, yungslaw, dshuds, llibrary, orelib, phosphor-lighting`

### Do you use any performance-enhancing mods (e.g. OptiFine)?
Yes, OptiFine.

**Comment by BlayTheNinth** [comment]
Minecraft 1.12 is no longer supported
