### ISSUE TITLE
Crashes when u die

### ISSUE THREAD

**Issue by 12MBTT** [blay09/HardcoreRevival#85]
### Minecraft Version

1.19.x

### Mod Loader

Fabric

### Mod Loader Version

0.14.10

### Mod Version

9.0.0

### Describe the Issue

Game crashes when I K.O'd

### Logs

[latest.log](https://github.com/ModdingForBlockheads/HardcoreRevival/files/10055615/latest.log)

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

I just have fabric api, hardcore revival, balm and cloth config api

**Comment by marewey** [comment]
Having same issue. After crashing the first time, and reloading the world I hit Accept fate, it puts me at 1 heart and then I die again and crash. Hope someone can fix this. Thanks in advance!

**Comment by 12MBTT** [comment]
> Having same issue. After crashing the first time, and reloading the world I hit Accept fate, it puts me at 1 heart and then I die again and crash. Hope someone can fix this. Thanks in advance!

I hope so :) This mod is extremely good for hardcore survival I hope they see and fix this issue.
