### ISSUE TITLE
Catalogue/Configured does not work as intended with Hardcore Revival

### ISSUE THREAD

**Issue by DeshiDesu** [blay09/HardcoreRevival#93]
### Minecraft Version

1.19 - 1.19.2

### Mod Loader

Forge

### Mod Loader Version

43.1.64

### Mod Version

9.0.1

### Describe the Issue

![Screenshot from 2022-12-17 15-49-48](https://user-images.githubusercontent.com/120287925/208265537-575172c4-f2fb-49b9-aa2b-5f0cac060058.png)
Normally you would have the searchbar on top of the list instead of below, as well as having the config button. With Hardcore Revival removed, Catalogue and Configured works as intended.

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

Optifine

**Comment by BlayTheNinth** [comment]
Fixed in latest Balm version
