### ISSUE TITLE
Add option to instantly die (skip mod) when one is the only one in the world/on the server

### ISSUE THREAD

**Issue by TobiPeterG** [blay09/HardcoreRevival#95]
Hey there, I noticed that the revival screen also appears when I'm playing alone where I can't be rescued by friends anyway.
It would be great if there was an option to disable the mod functionality when playing alone.

**Comment by BlayTheNinth** [comment]
Related to #62, there should probably be two options, one for singleplayer (default on) and one for lonely multiplayer (default off).
