### ISSUE TITLE
[1.19.2] Incompatibility w/ Catalogue (MrCrayfish mod)

### ISSUE THREAD

**Issue by shipwithpremier** [blay09/HardcoreRevival#96]
### Minecraft Version

1.19 - 1.19.2

### Mod Loader

Forge

### Mod Loader Version

43.2.3

### Mod Version

9.0.1

### Describe the Issue

The Hardcore Revival mod appears to break Catalogue, which is a client-sided mod that replaces the in-game Mods list screen with a custom/improved version. I have no idea what HCR would be doing that could break it but nevertheless I tested it with only Catalogue and HardcoreRevival (+Balm dependency) and it breaks.

https://curseforge.com/minecraft/mc-mods/catalogue

### Logs

https://pastebin.com/yingg1VM

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

None (tested using only Catalogue and HCR/Balm)

**Comment by BlayTheNinth** [comment]
Fixed in latest Balm version
