### ISSUE TITLE
Relogging with Spice of Life: Sweet Potato revives you

### ISSUE THREAD

**Issue by GreenForzeGaming** [blay09/HardcoreRevival#97]
### Minecraft Version

1.19 - 1.19.2

### Mod Loader

Forge

### Mod Loader Version

43.2.0

### Mod Version

9.0.1

### Describe the Issue

when installed with Spice of life sweet potato, logging of and back in skips the whole revival secuence and your alive again with everything still on you.

**Comment by BlayTheNinth** [comment]
Closing since 1.19 is no longer supported.
