### ISSUE TITLE
KO player still can place block, shoot bow(and kill mob), use chest

### ISSUE THREAD

**Issue by MilkissWhite** [blay09/HardcoreRevival#98]
### Minecraft Version

1.19.3

### Mod Loader

Fabric

### Mod Loader Version

0.14.17

### Mod Version

10.0.0

### Describe the Issue

1. KO by monster
2. push ESC key. 'accept your fate' button disappear.
3. select hot bar & use items.
4-1. you can click with bare hand but attack can not hit enemy while 'allow unarmed melee=false'
4-2. you can draw bow and shoot. arrow actually hurt monster. so you can kill monster even while 'allow bows=false'
4-3. you can place blocks. this means you can place chest. and also you can interact with chest. so you can store all your items in chest after you KO.

tested in singleplayer only. it seems some feature not working.

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

no. only difference I have is using CurseForge App for manage mods.

**Comment by BlayTheNinth** [comment]
Fixed in latest Balm version
